### ISSUE TITLE
I can't use $ref to pull in other yaml files

### ISSUE THREAD

**Issue by evhabs** [openapi-library/OpenAPIValidators#238]
**Which package are you using**?
`chai-openapi-response-validator` / `jest-openapi`

**OpenAPI version**
3

**Describe the bug**
In my response I try to use $ref to ask for a model and i consistantly get this error: 
` received did not satisfy it because: products[0] can't resolve reference ./models/Product.v1.yaml`

I've tried moving it into the same folder and doing './Product.v1.yaml' but it still doesn't work.

Here is part of my reference file that is in question: 
```
  /products:
    get:
      summary: List products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: './Product.v1.yaml'

```

Is this type of notation supported? Or do I need to have items: point to something like `$ref: '#/definitions/ComponentType/Product'`

**To Reproduce**

1. Create a yaml file
2. create a yaml model in a different folder
3. use $ref in response to reference it
4. See error when you try doing:
`    expect(res).toSatisfyApiSpec();`

**Expected behavior**
I expected it to find the yaml file and do correct comparisons against my API doc

**Are you going to resolve the issue?**

If it something that needs to be added I don't mind taking a look

**Comment by rwalle61** [comment]
Hey @evhabs, thanks for raising this, did you resolve the issue?

**Comment by evhabs** [comment]
Hey @rwalle61, I wasn't able to resolve this I closed this because it seems there's already this same issue here:  https://github.com/openapi-library/OpenAPIValidators/issues/229

**Comment by rwalle61** [comment]
Sorry for the delay! I think your issue is quite different to #229, which is about what to do when the request path matches multiple paths in the OpenAPI document. Your issue is that you want to reference other files via `$ref: './Product.v1.yaml'`. Unfortunately we don't currently support this - when we see `$ref` we just look at [`#/components/responses/`](https://github.com/openapi-library/OpenAPIValidators/blob/master/packages/openapi-validator/lib/classes/OpenApi3Spec.ts#L81) rather than other files.

If you'd like this enhancement (or bug fix, whatever you want to call it), a PR would be very welcome 😄 

You could either expand that function to recognise file refs and look in those files, or ideally there'd be some npm package to manage that complexity for us. Here are [some docs](https://swagger.io/docs/specification/using-ref/)I found on how `$ref` should behave

**Comment by rwalle61** [comment]
Actually, is this a duplicate of https://github.com/openapi-library/OpenAPIValidators/issues/216 ? (perhaps you meant to link that instead of 229). Does the workaround in #216 solve this issue?

**Comment by evhabs** [comment]
Oh I didn't see #216  i'll have to try this out when I get sometime later this week i'll try it out
